* EAZY-Project - Interactive Project Generator & Manager

This used to be a fork from cl-project@fukamachi, but since almost everything is
rewritten and added very much of new features, I renamed it as a new library.
*I use it for myself.* It is now focused on lots of interactive features.

Usage:
#+BEGIN_SRC 
(ql:quickload :eazy-project.autoload)
;; no command is required, all you need is to load the library

;; if you do not want to launch a menu (and only to load the library),
(ql:quickload :eazy-project)

;; to launch a menu maually,
(eazy-project:launch-menu) ; or
eazy-project:!             ; use this synonym

;;; Then, follow the instruction in the menu that appears in the debugger.
#+END_SRC

Tested on SBCL-1.2.1 x64 and CCL 1.9 x64.

** To load w/o automatically launching the menu

=(ql:quickload :eazy-project.impl)= does not launch the menu.

** Installation

To load this library, clone the repo into the quicklisp's local-project
directory and run
=(ql:register-local-project)(ql:quickload :eazy-project)=.

** Tutorial: Restore the Yesterday's Coding Environment

RYCE feature saves and restores the set of currently loaded libraries.
In the main menu, select the =SESSION= submenu.

Main menu:
#+BEGIN_SRC 
(You are now in menu EP-MAIN.)
What to do next?
...
...
...
   [Condition of type EAZY-PROJECT:ASK]

Restarts:
 0: [SESSION] Save/Restore the currently loaded libraries
 1: [CREATE-PROJECT] Create a new project.
 2: [SET-GLOBAL] Modify these default values
 3: [UP] Back to the section EP-MAIN.
 4: [QUIT-SESSION] Quit this session.
 5: [RETRY] Retry SLIME REPL evaluation request.
#+END_SRC

SESSION submenu:
#+BEGIN_SRC 
(You are now in menu SESSION.)
What to do next?
   [Condition of type EAZY-PROJECT:ASK]

Restarts:
 0: [TOGGLE-WATCH] Watch and automatically save the session
 1: [ADD-DEFAULT-SYSTEM] Add-Default-System
 2: [SAVE] Save the current loaded session
 3: [ABORT] Return to sldb level 1.
 4: [UP] Back to the section EP-MAIN.
 5: [QUIT-MENU] Quit this eazy-project menu.
#+END_SRC

Then, SAVE or RESTORE the current session. SAVE will store the current
=*package*= and =asdf:already-loaded-systems= to a database for the later
restoration. RESTORE will restore the saved session. Finally, TOGGLE-WATCH
will initiate watching, which periodically initiate the SAVE command.

** Tutorial: Generate a project

First, open the menu.
The default data will have already been customized for you.
It should look something like this (depending on the implementation).

#+BEGIN_SRC 
(You are now in menu EP-MAIN.)
What to do next?

Here are current default configs:
:SESSION.SYSTEMS     = (...
                        "fare-quasiquote")
:SESSION.PACKAGE     = "COMMON-LISP-USER"
:LOCAL-REPOSITORY    = #P"/mnt/video/guicho/repos/lisp/"
:SKELETON-DIRECTORY  = #P"/mnt/video/guicho/repos/lisp/eazy-project/skeleton"
:AUTHOR              = "Masataro Asai"
:EMAIL               = "guicho2.71828@gmail.com"
:GIT                 = T
:README-EXTENSION    = "md"
:SOURCE-DIR          = "src"
:TEST-DIR            = "t"
:TEST-SUBNAME        = "test"
:DELIMITER           = "."
:LICENSE             = "LLGPL"
:TEST                = :FIVEAM
:DEPENDS-ON          = (:ALEXANDRIA :OPTIMA :ITERATE)
   [Condition of type EAZY-PROJECT:ASK]

Restarts:
 0: [SESSION] Save/Restore the currently loaded libraries
 1: [CREATE-PROJECT] Create a new project.
 2: [SET-GLOBAL] Modify these default values
 3: [UP] Back to the section EP-MAIN.
 4: [QUIT-SESSION] Quit this session.
 5: [RETRY] Retry SLIME REPL evaluation request.
#+END_SRC

Select =CREATE-PROJECT=, a new debugger menu would appear. 

#+BEGIN_SRC 
(You are now in menu CREATE-PROJECT.)
Select and enter the information, then select 'CREATE'.
Current global configuration:
....

Current local configuration:
(no configuration specified)
   [Condition of type EAZY-PROJECT:ASK]

Restarts:
 0: [CREATE] Create
 1: [RESET-LOCAL-CONFIG] Reset the current local config
 2: [ADD-LOCAL-DEPENDENCY] Add-Local-Dependency
 3: [NAME] Name
...
#+END_SRC

In this submenu, you can further modify several /project-local/
configurations. These configurations are not memorised into the database.

+ Select =NAME= to enter the name of the new project (if when you attempt
  to create a project without it, the generator complains and opens an
  interactive prompt).
+ You can further add the dependencies.
  + The project-local dependency (only for this project) can be added by
    ADD-LOCAL-DEPENDENCY submenu.
  + The default dependency can be
    customized in the menu =EP-MAIN -> SET-GLOBAL=.
  + The default dependency can be modified by editing the customization
    file directly. It is saved in
    =<eazy-project-repo>/default-config.lisp=.

Finally, select =CREATE=. It will set up the repository, initialize the
repo with git (by default. It can be disabled).

